import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { DebugBlock } from './blockAnalyzer.js';

export interface GeneratedTest {
  filePath: string;
  code: string;
}

/**
 * Normalizes import specifiers in an import statement to absolute paths if they are relative.
 * E.g., `import { LoginPage } from './LoginPage'` -> `import { LoginPage } from 'C:/.../LoginPage'`
 */
export function normalizeImportStatement(importStmt: string, sourceFilePath: string): string {
  const dir = path.dirname(sourceFilePath);

  // Regex to match relative module specifiers: from './...' or from '../...'
  return importStmt.replace(/(from\s+['"])((\.|\.\.)\/[^'"]+)(['"])/g, (_match, prefix, relPath, _dot, suffix) => {
    const absPath = path.resolve(dir, relPath).replace(/\\/g, '/');
    return `${prefix}${absPath}${suffix}`;
  });
}

/**
 * Generates the full TypeScript code string for executing a DebugBlock standalone against CDP.
 */
export function generateTempTestCode(block: DebugBlock, cdpConnectModulePath?: string): string {
  const lines: string[] = [];

  lines.push('// Auto-generated by Playwright Debug Block VS Code Extension');
  lines.push('// DO NOT EDIT MANUALLY\n');

  // 1. Module Imports
  lines.push('// --- Imports ---');
  for (const imp of block.imports) {
    lines.push(normalizeImportStatement(imp, block.filePath));
  }

  // Import cdpConnect helper
  const cdpPath = cdpConnectModulePath
    ? cdpConnectModulePath.replace(/\\/g, '/')
    : path.resolve(__dirname, 'cdpConnect.js').replace(/\\/g, '/');
  lines.push(`import { getFixtureBindings } from '${cdpPath}';\n`);

  // 2. Resolved Dependencies (helpers, POM classes, pre-requisite variables)
  if (block.dependencies.length > 0) {
    lines.push('// --- Resolved Dependencies ---');
    for (const dep of block.dependencies) {
      lines.push(dep.text);
    }
    lines.push('');
  }

  // 3. Execution Wrapper Function
  lines.push('// --- Debug Block Execution ---');
  lines.push(`async function runDebugBlock_${block.name.replace(/[^a-zA-Z0-9_$]/g, '_')}() {`);

  // Retrieve required fixtures
  if (block.requiredFixtures.length > 0) {
    const fixtureList = block.requiredFixtures.join(', ');
    lines.push(`  console.log('[PW-DEBUG] Connecting to CDP and retrieving fixtures: ${fixtureList}...');`);
    lines.push(`  const bindings = await getFixtureBindings([${block.requiredFixtures.map(f => `'${f}'`).join(', ')}]);`);
    for (const fixture of block.requiredFixtures) {
      lines.push(`  const ${fixture} = bindings.${fixture};`);
    }
  } else {
    lines.push(`  console.log('[PW-DEBUG] Running block without fixtures...');`);
  }

  lines.push(`  console.log('[PW-DEBUG] Executing debug block: "${block.name}"');`);
  lines.push('  ');

  // Statement code execution block
  // We indent statements inside the runner function
  for (const dep of block.dependencies) {
    // If a dependency statement was a variable declaration needed inside scope, it's already added at top or can be in function
  }

  // Extract statement text from AST nodes or reconstructed source
  // Each block statement source code is rendered here
  lines.push('  // Block Code');
  // We will pass the block statements' text in block object or extract statement text
  if ((block as any).codeText) {
    lines.push((block as any).codeText);
  }

  lines.push('  console.log(\'[PW-DEBUG] Debug block completed successfully.\');');
  lines.push('}');

  lines.push('\n// Execute runner');
  lines.push(`runDebugBlock_${block.name.replace(/[^a-zA-Z0-9_$]/g, '_')}().catch(err => {`);
  lines.push('  console.error(\'[PW-DEBUG] Execution Error:\', err);');
  lines.push('  process.exit(1);');
  lines.push('});');

  return lines.join('\n');
}

/**
 * Creates a temporary TypeScript test file on disk and returns its file path and generated code.
 */
export function createTempTestFile(
  block: DebugBlock,
  codeText: string,
  targetDir?: string,
  cdpConnectModulePath?: string
): GeneratedTest {
  const dir = targetDir || os.tmpdir();
  const tempFolder = fs.mkdtempSync(path.join(dir, 'pw-debug-'));
  const safeName = block.name.replace(/[^a-zA-Z0-9_-]/g, '_');
  const tempFilePath = path.join(tempFolder, `debug_${safeName}.ts`);

  // Store codeText on block for code generation
  (block as any).codeText = codeText;

  const fullCode = generateTempTestCode(block, cdpConnectModulePath);
  fs.writeFileSync(tempFilePath, fullCode, 'utf8');

  return {
    filePath: tempFilePath,
    code: fullCode,
  };
}
